// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"SFGPL-End/biz/model"
)

func newCategorie(db *gorm.DB, opts ...gen.DOOption) categorie {
	_categorie := categorie{}

	_categorie.categorieDo.UseDB(db, opts...)
	_categorie.categorieDo.UseModel(&model.Categorie{})

	tableName := _categorie.categorieDo.TableName()
	_categorie.ALL = field.NewAsterisk(tableName)
	_categorie.ID = field.NewInt32(tableName, "id")
	_categorie.Name = field.NewString(tableName, "name")
	_categorie.UpdateTime = field.NewTime(tableName, "update_time")
	_categorie.CreateTime = field.NewTime(tableName, "create_time")
	_categorie.IsDeleted = field.NewField(tableName, "is_deleted")

	_categorie.fillFieldMap()

	return _categorie
}

type categorie struct {
	categorieDo

	ALL        field.Asterisk
	ID         field.Int32  // 分类id
	Name       field.String // 分类名
	UpdateTime field.Time   // 更新时间
	CreateTime field.Time   // 创建时间
	IsDeleted  field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (c categorie) Table(newTableName string) *categorie {
	c.categorieDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c categorie) As(alias string) *categorie {
	c.categorieDo.DO = *(c.categorieDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *categorie) updateTableName(table string) *categorie {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.Name = field.NewString(table, "name")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.CreateTime = field.NewTime(table, "create_time")
	c.IsDeleted = field.NewField(table, "is_deleted")

	c.fillFieldMap()

	return c
}

func (c *categorie) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *categorie) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["is_deleted"] = c.IsDeleted
}

func (c categorie) clone(db *gorm.DB) categorie {
	c.categorieDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c categorie) replaceDB(db *gorm.DB) categorie {
	c.categorieDo.ReplaceDB(db)
	return c
}

type categorieDo struct{ gen.DO }

type ICategorieDo interface {
	gen.SubQuery
	Debug() ICategorieDo
	WithContext(ctx context.Context) ICategorieDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICategorieDo
	WriteDB() ICategorieDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICategorieDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICategorieDo
	Not(conds ...gen.Condition) ICategorieDo
	Or(conds ...gen.Condition) ICategorieDo
	Select(conds ...field.Expr) ICategorieDo
	Where(conds ...gen.Condition) ICategorieDo
	Order(conds ...field.Expr) ICategorieDo
	Distinct(cols ...field.Expr) ICategorieDo
	Omit(cols ...field.Expr) ICategorieDo
	Join(table schema.Tabler, on ...field.Expr) ICategorieDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICategorieDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICategorieDo
	Group(cols ...field.Expr) ICategorieDo
	Having(conds ...gen.Condition) ICategorieDo
	Limit(limit int) ICategorieDo
	Offset(offset int) ICategorieDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICategorieDo
	Unscoped() ICategorieDo
	Create(values ...*model.Categorie) error
	CreateInBatches(values []*model.Categorie, batchSize int) error
	Save(values ...*model.Categorie) error
	First() (*model.Categorie, error)
	Take() (*model.Categorie, error)
	Last() (*model.Categorie, error)
	Find() ([]*model.Categorie, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Categorie, err error)
	FindInBatches(result *[]*model.Categorie, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Categorie) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICategorieDo
	Assign(attrs ...field.AssignExpr) ICategorieDo
	Joins(fields ...field.RelationField) ICategorieDo
	Preload(fields ...field.RelationField) ICategorieDo
	FirstOrInit() (*model.Categorie, error)
	FirstOrCreate() (*model.Categorie, error)
	FindByPage(offset int, limit int) (result []*model.Categorie, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICategorieDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c categorieDo) Debug() ICategorieDo {
	return c.withDO(c.DO.Debug())
}

func (c categorieDo) WithContext(ctx context.Context) ICategorieDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categorieDo) ReadDB() ICategorieDo {
	return c.Clauses(dbresolver.Read)
}

func (c categorieDo) WriteDB() ICategorieDo {
	return c.Clauses(dbresolver.Write)
}

func (c categorieDo) Session(config *gorm.Session) ICategorieDo {
	return c.withDO(c.DO.Session(config))
}

func (c categorieDo) Clauses(conds ...clause.Expression) ICategorieDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categorieDo) Returning(value interface{}, columns ...string) ICategorieDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categorieDo) Not(conds ...gen.Condition) ICategorieDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c categorieDo) Or(conds ...gen.Condition) ICategorieDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c categorieDo) Select(conds ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c categorieDo) Where(conds ...gen.Condition) ICategorieDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c categorieDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) ICategorieDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c categorieDo) Order(conds ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c categorieDo) Distinct(cols ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categorieDo) Omit(cols ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categorieDo) Join(table schema.Tabler, on ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categorieDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categorieDo) RightJoin(table schema.Tabler, on ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categorieDo) Group(cols ...field.Expr) ICategorieDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c categorieDo) Having(conds ...gen.Condition) ICategorieDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c categorieDo) Limit(limit int) ICategorieDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c categorieDo) Offset(offset int) ICategorieDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c categorieDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICategorieDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categorieDo) Unscoped() ICategorieDo {
	return c.withDO(c.DO.Unscoped())
}

func (c categorieDo) Create(values ...*model.Categorie) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categorieDo) CreateInBatches(values []*model.Categorie, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categorieDo) Save(values ...*model.Categorie) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categorieDo) First() (*model.Categorie, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Categorie), nil
	}
}

func (c categorieDo) Take() (*model.Categorie, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Categorie), nil
	}
}

func (c categorieDo) Last() (*model.Categorie, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Categorie), nil
	}
}

func (c categorieDo) Find() ([]*model.Categorie, error) {
	result, err := c.DO.Find()
	return result.([]*model.Categorie), err
}

func (c categorieDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Categorie, err error) {
	buf := make([]*model.Categorie, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categorieDo) FindInBatches(result *[]*model.Categorie, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categorieDo) Attrs(attrs ...field.AssignExpr) ICategorieDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categorieDo) Assign(attrs ...field.AssignExpr) ICategorieDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categorieDo) Joins(fields ...field.RelationField) ICategorieDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c categorieDo) Preload(fields ...field.RelationField) ICategorieDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c categorieDo) FirstOrInit() (*model.Categorie, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Categorie), nil
	}
}

func (c categorieDo) FirstOrCreate() (*model.Categorie, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Categorie), nil
	}
}

func (c categorieDo) FindByPage(offset int, limit int) (result []*model.Categorie, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categorieDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c categorieDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c categorieDo) Delete(models ...*model.Categorie) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *categorieDo) withDO(do gen.Dao) *categorieDo {
	c.DO = *do.(*gen.DO)
	return c
}
