// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProgram = "program"

// Program mapped from table <program>
type Program struct {
	ID          int32          `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:书籍id" json:"id,string"`
	Title       string         `gorm:"column:title;type:varchar(255);not null;comment:书籍名" json:"title"`
	View        string         `gorm:"column:view;type:varchar(255);not null;comment:书籍简介" json:"view"`
	ActorID     int32          `gorm:"column:actor_id;type:int(11) unsigned;not null;comment:作者id" json:"actor_id"`
	CategorieID int32          `gorm:"column:categorie_id;type:int(11) unsigned;not null;comment:分类id" json:"categorie_id"`
	UpdeateTine time.Time      `gorm:"column:updeate_tine;type:datetime;comment:更新时间" json:"updeate_tine"`
	CreateTime  time.Time      `gorm:"column:create_time;type:datetime;comment:创建时间" json:"create_time"`
	IsDeleted   gorm.DeletedAt `gorm:"column:is_deleted;type:datetime;comment:删除时间" json:"is_deleted"`
}

// TableName Program's table name
func (*Program) TableName() string {
	return TableNameProgram
}
